### PR TITLE
SetupStringParameters sets with specifier

### PR DESCRIPTION
**Pull request by noche-x**
First off im new to using github and I'm sorry if I'm doing this wrong.

Before:
csgo_2019-03-10_22-54-02

After: 
NVIDIA_Share_2019-03-10_22-58-23

### CODE REVIEW

**Comment by kwilcz** [comment]
Thanks for that pr, just 1 quick thing - please replace 8space tab with 4space for consistency :)

**Comment by noche-x** [comment]
I think it's a bug where there are 8 spacings. It's normal on my source but not on github. No problem :)

**Comment by kwilcz** [comment]
MSVC shows tab always as 4 spaces, no matter how big the spacing is.
Change settings to these, and then reformat.
image

**Comment by kwilcz** [comment]
After some testing of this:
- Yours:
image

- Old one:
image

I don't know why you have an issue with the "1" showing up at the end. With multiple tests - it doesnt show up on my side.
+ the code you've added just removes 1 character after the found %.
Perhaps it needs some further debugging.

**Comment by noche-x** [comment]
As i posted on my screenshot for example when i 
`
int testintegervalue = 123;
Utils::Log("test %i", testintegervalue);
`
it outputs like 
`
test 123i
`
so when i remove the char after % it will fix it for me

**Comment by noche-x** [comment]
But as i examine it for the second time its not like printf. Silly me % just works fine.

**Comment by kwilcz** [comment]
It doesnt work 1:1 like printf, no need for type specifiers.
Closing as issue got resolved.

**Pull request closed without merging**
