### PR TITLE
Versionless Interfaces

### PR DESCRIPTION
**Pull request by Pocakking**
No need to update the interface versions anymore.

### CODE REVIEW

**Comment by kwilcz** [comment]
For me it's kinda an useless feature only affecting performance since you can dump these in ~30sec.
Will wait for other opinions tho.

**Comment by Pocakking** [comment]
Updated it for the logger update.

**Comment by certmemer** [comment]
let's see how much of our precious time can we shave off with this epic codenz for something that is updated AT BEST once a year and verry difficult to find on our own, shall we?
https://vgy.me/uDXdhG.gif world record run, 88 tries to get time this good!

**Comment by memecado** [comment]
I'm not sure where I'd ask this but this is a place where I can comment so I'll ask here, how do I use this? I'm really new to csgo cheating so im not sure how to inject this into the game. Any help would be appreciated, thank you

**Comment by kwilcz** [comment]
Closing PR, see above for reasoning.

**Pull request closed without merging**
